spring.application.name=FirstSpring
spring.h2.console.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb
spring.datasource.username=asr003
spring.datasource.password=Saquib@123
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-dialect=org.hibernate.dialect.PostgresSQLDialect
management.endpoints.web.exposure.include=*
endpoint.health.show-details=always

